version: '3'
services:
  pg:
    image: 'postgres:16.2'
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
  ror:
    build:
      dockerfile: ./Dockerfile.prod
    environment:
      RAILS_ENV: production
  ngx:
    volumes:
      - ./ngx/production.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '443:443'
secrets:
  pg_secrets:
    file: ./pg_secrets