default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials[:pg][:user] %>
  host: <%= Rails.application.credentials[:pg][:host] %>
  database: <%= Rails.application.credentials[:pg][:database] %>
  port: <%= Rails.application.credentials[:pg][:port] %>
  password: <%= Rails.application.credentials[:pg][:password] %>
  pool: 5

development:
  primary:
    <<: *default
    database: bahasa_dev
  cable:
    <<: *default
    database: bahasa_dev_cable
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: ror_test

production:
  primary:
    database: bahasa_prod
  cable:
    <<: *default
    database: bahasa_prod_cable
    migrations_paths: db/cable_migrate